### PR TITLE
Adding Method.Signature and backward compatibility with it

### PR DESCRIPTION
**Pull request by Adrien-COSTANDI**

### CODE REVIEW

**Comment by forax** [comment]
I do not think it's a good idea to include modifiers, etc in the signature.
A signature of a method is only the return type and the parameters type.

The code is already compiled so the modifiers have already been checked by compiler, the return type has already been found by the compiler, etc

**Comment by Adrien-COSTANDI** [comment]
I understand, but we need the modifiers at runtime to know if a method call is public to display it in the sequence diagram

**Comment by forax** [comment]
Yes, but it can stay at the method level

**Comment by Adrien-COSTANDI** [comment]
We want the Call.MethodCall to store the Signature instead of _String name, TypeInfo returnType, List<TypeInfo> parameterTypes_ so that when we look for the method call, we can know if the method is public.
The Call.MethodCall doesn't store anything that can tell if the method is public or not

**Comment by forax** [comment]
The matching between a declared method and a method call uses the method name and descriptor, which is the erasure of the method signature, not the type info which also contains thing like parameterized types and type variables. 
I think it's better to store the method descriptor in the object Method and lookup for it using (name + descriptor).
The other solution is to erase the returnType and parameter type to re-create the descriptor.

**Comment by forax** [comment]
I've changed the code classes to use descriptor.

And move the code you have added into the core class elsewhere because they are not related to any data so should not be inside the records defined the data

**Pull request closed without merging**
