### PR TITLE
merge VELU-VIEXIAU

### PR DESCRIPTION
**Pull request by tvelu77**
adding plantuml and mermaiduml support (can now draw box) and fixed checkstyle error

### CODE REVIEW

**Comment by forax** [comment]
Having one class for each display, (plantUML and mermaid) will make the code easier to understand and will localise the change

**Comment by forax** [comment]
You also have to fix those two issues reported by CheckStyle
[WARN] /home/runner/work/umldoc/umldoc/src/main/java/com/github/veluvexiau/umldoc/core/Main.java:55:3: 'METHOD_DEF' should be separated from previous line. [EmptyLineSeparator]
[WARN] /home/runner/work/umldoc/umldoc/src/main/java/com/github/veluvexiau/umldoc/core/Main.java:66:3: 'METHOD_DEF' should be separated from previous line. [EmptyLineSeparator]

**Review by tvelu77 — COMMENTED** [review]
added classes to make the program easier to read and fixed checkstyle errors

**Comment by forax** [comment]
The interface is useless (at least for now) and too complex, please remove it and only keep the two classes with only one public method per class

**Pull request merged**
