### PR TITLE
feat: add mermaid class diagram (PEREIRA - VL)

### PR DESCRIPTION
**Pull request by PereiraE**
This PR add the Mermaid class diagram of the group PEREIRA - Thomas (VL)

### CODE REVIEW

**Comment by forax** [comment]
Please add a text to this PR, i will not accept a PR with no text.

The choice of the color makes the diagram not readable
- the background is black, please use a light color for the background and
- the association are using a light gray instead of a solid black.

And the associations are not named ??

**Comment by forax** [comment]
The names of the associations are the name of the fields that support the association, so verbs are prohibited.

**Comment by PereiraE** [comment]
Changed the associations names to field name

**Comment by forax** [comment]
Can you also add the mermaid file, given that ultimately, it is this format that should be generated ?

**Comment by PereiraE** [comment]
Added a .md file in a new folder (design/mermaid_files) containing the mermaid definition of the diagram

**Comment by forax** [comment]
The declaration of the fields are, i believe, in the wrong order, it should be "name" "type" and not "type" "name" in UML
Anyway, i've accepted your PR.

**Pull request merged**
